# Generated by Django 5.2.1 on 2025-06-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
                ('passcode', models.CharField(max_length=255)),
            ],
        ),
    ]
